#!/usr/bin/env bash

if [ -z $1 ]; then
    echo "usage: $0 <migration-name>"
    exit 1
fi

mkdir -p migrations
migration_files=($(ls migrations))
migration_filename=$(printf "migrations/%04d-$1.sql" ${#migration_files[@]})
touch $migration_filename 
